image:
  file: .gitpod.Dockerfile
tasks:
  - name: rstudio
    before: |
      echo R_LIBS_USER=$GITPOD_REPO_ROOT/../.R/library > /home/gitpod/.Renviron
      cp .gitpod/.Rprofile /home/gitpod/  
      echo 'RSTUDIO_CONFIG_DIR=/workspace/advanced-data-analysis/.gitpod' >> /home/gitpod/.profile
    command: /usr/lib/rstudio-server/bin/rstudio-server start
  - name: R
    command: R
ports:
  - port: 8787
    onOpen: open-browser
  - port: 3000-8786
    onOpen: ignore
  - port: 8786-15000
    onOpen: ignore 
github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod
    
